---
version: "2.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.47 # optional
    volumes:
      - ${PWD}/config:/config # optional
      - ${PWD}/assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8088:80 #optional
    restart: unless-stopped